language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
  - "pypy"

install:
  - pip install -r requirements-test.txt

script:
  - python -m unittest discover -s tests
  - coverage run run_tests.py && coverage report -m

notifications:
  email: false